name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        description: "Mensaje de entrada"
        required: true
        type: string
      number:
        description: "Número de entrada"
        required: true
        type: number
    secrets:
      MY_SECRET:
        description: "Secreto para usar en el workflow"
        required: true

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar parámetros y secreto
        run: |
          echo "Mensaje: ${{ inputs.message }}"
          echo "Número: ${{ inputs.number }}"
          echo "Secreto: ${{ secrets.MY_SECRET }}"
