on:
  workflow_call:
    inputs:
      origin_organization:
        type: string
        required: false
      destination_organization:
        type: string
        required: false
      origin_repository:
        type: string
        required: false
      destination_repository:
        type: string
        required: false
    secrets:
      GH_TOKEN_DESTINATION_REPOSITORY:
        required: true

jobs:
  sync-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Git
        run: |
          pwd
